/*
 * REQUERIMIENTOS
 * -Debe mostrar una pantalla con el listado de Facturas con los datos
 *  de Fecha, Numero Factura, Nombre Cliente y Total en ese orden.
 * -Debe permitir crear una factura nueva en la cual ingrese todos los
 *  datos correspondientes a la factura y a los detalles. La base de 
 *  datos debe contar con al menos 6 productos que pueden ser 
 *  precargados en la tabla Productos.
 * -En la creación de cada factura debe calcular el Total Descuento, 
 *  Total Impuesto y el Total de acuerdo a los datos ingresados en el
 *  formulario de creación de factura.
 * -Debe permitir editar y eliminar una factura. (La vista para Editar
 *  puede ser la misma de Crear).
 * -No es necesario hacer un formulario para crear productos, éstos se
 *  pueden insertar directamente en la base de datos.
 * -Debe validar que no ingrese una fecha anterior al día actual, que
 *  ingrese al menos un detalle, que la cantidad de productos sea mayor
 *  a 0 y que el Precio Unitario no sea negativo.
 */
package view;

/**
 *
 * @author scorpion
 */
public class VwMenu extends javax.swing.JFrame {

    /**
     * Creates new form VwMenu
     */
    public VwMenu() {
        initComponents();
        inicio();
    }
    
    void inicio(){
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    
    void ejecutarFG(){
        VwFacturasGeneradas vfg=new VwFacturasGeneradas(this, true);
        vfg.setLocationRelativeTo(null);
        vfg.setVisible(true);
    }
    
    void ejecutarF(){
        VwFacturas vf=new VwFacturas(this, true);
        vf.setLocationRelativeTo(null);
        vf.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblimage = new javax.swing.JLabel();
        mnbmenu = new javax.swing.JMenuBar();
        mngestionfacturacion = new javax.swing.JMenu();
        mntfacturasgeneradas = new javax.swing.JMenuItem();
        mntfacturar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Facturación");

        lblimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/globaltek.png"))); // NOI18N

        mngestionfacturacion.setText("Gestión de facturación");

        mntfacturasgeneradas.setText("Facturas Generadas");
        mntfacturasgeneradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntfacturasgeneradasActionPerformed(evt);
            }
        });
        mngestionfacturacion.add(mntfacturasgeneradas);

        mntfacturar.setText("Facturar");
        mntfacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntfacturarActionPerformed(evt);
            }
        });
        mngestionfacturacion.add(mntfacturar);

        mnbmenu.add(mngestionfacturacion);

        setJMenuBar(mnbmenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblimage, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblimage, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mntfacturasgeneradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntfacturasgeneradasActionPerformed
        // TODO add your handling code here:
        ejecutarFG();
    }//GEN-LAST:event_mntfacturasgeneradasActionPerformed

    private void mntfacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntfacturarActionPerformed
        // TODO add your handling code here:
        ejecutarF();
    }//GEN-LAST:event_mntfacturarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VwMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VwMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VwMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VwMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VwMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblimage;
    private javax.swing.JMenuBar mnbmenu;
    private javax.swing.JMenu mngestionfacturacion;
    private javax.swing.JMenuItem mntfacturar;
    private javax.swing.JMenuItem mntfacturasgeneradas;
    // End of variables declaration//GEN-END:variables
}
